== Conditionals

Lets simulate tossing a coin and print `Heads` or `Tails` with a 50-50 chance.

The `random` module contains many functions for generating random numbers. The function `random.random()` returns a `uniform` floating-point number between 0 and 1.

NOTE: A random number generator is _uniform_ if all outcomes are equally likely.

[source,python,numbered]
----
import random
print(random.random())
----

 0.2840077963246783

The function `random.randrange(n)` returns a _uniform_ random integer between 0 and `n-1` inclusive. 

[source,python,numbered]
----
import random
print(random.randrange(6))
----

 5

We need some way to check what the random number generator produced.
The _if-statement_ executes one of two possible blocks of statements depending on a logical condition.

[source,python,subs="quotes"]
----
if (*_condition_*):
    true_stmts
else:
    false_stmts
----

If the condition is true then the block of statements labeled `true_stmts` will be executed, otherwise the block of statements labeled `false_stmts` will be executed. The `else` part is optional.  `if` and `else` are new _keywords_. They cannot be used as variable or function names. Notice also that the statements under the `if` of `else` are indented just like a function body or the body of a while loop.

Back to simulating a coin toss. Here is one way using `random.random()`

[source,python,numbered]
----
import random
x = random.random()

if x < 0.5:
    print("Heads") <1>
else:
    print("Tails")
----
<1> Assigning heads to be less than .5 is, of course, arbitrary. We could have just as easily made tails be less than .5.

Here is another way using `random.randrange()`

[source,python,numbered]
----
import random
x = random.randrange(2)

if x == 0:
    print("Heads") <1>
else:
    print("Tails")
----
<1> Similar to the above, assigning heads to be 0 is arbitrary.

Using either `random.random()` or `random.randrange()` is fine. One way is not particularly better than the other. Using `random.random()` makes it a little easier to simulate tossing an _unfair_ coin. For example, a coin that comes up heads two-thirds of the time. 

[source,python,numbered]
----
import random
x = random.random()

if x < 2/3:        <1>
    print("Heads")
else:
    print("Tails")
----
<1> If the random number generator is uniform then this should ensure that `x` is less than `2/3`, well, with probability `2/3`.

Using `random.randrange()` is a little tricker, but you can come close.
[source,python,numbered]
----
import random
x = random.randrange(1000)

if x < 667:         <1>
    print("Heads") 
else:
    print("Tails")
----
<1> Not exactly two-thirds, but close. How can we make it more accurate? 

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write a program that reads an integer from the keyboard and prints `even`, if the number was even, or `odd` if the number was odd. A number is even if it is divisible by two. That is, the remainder after dividing by two is zero.

[.result]
====
[source,python,numbered]
----
n = int(input("Enter an integer: "))

if n % 2 == 0:
    print(n, "is even")
else:
    print(n, "is odd")
----
====

=== if-elif-else

Lets take an example of tossing a single die footnote:[_die_ is the singular of the plural _dice_, one die, pair of dice.]. We will print `one` if we rolled a one, `two` if we rolled a two, etc. One way to write this:

[source,python,numbered]
----
import random

d = random.randrange(6) + 1
if d == 1:
    print("one")
else:
    if d == 2:
        print("two")
    else:
        if d == 3:
            print("three")
        else:
            if d == 4:
                print("four")
            else:
                if d == 5:
                    print("five")
                else:
                    print("six")
----

This is pretty confusing and not very readable. Most programming languages have an alternative form of the if-statement that we sometimes call _if-else-if_. Here is Python's version:

[source,python,subs="quotes"]
----
if (*_condition1_*):
    stmts1
elif (*_condition2_*):
    stmts2
elif (*_condition3_*):
    stmts3

	...
	
else:             
    stmts_else
----

The final `else` clause is optional. Note the new keyword `elif`.  `condition1` is checked first and if it is true then `stmts` is executed, and the remainder of the if-elif-statement is skipped. If `condition1` is false we check `condition2` and so on. 

Now we can write our die toss program as:

[source,python,numbered]
----
d = random.randrange(6) + 1
if d == 1:                 
    print("one")
elif d == 2:                  
    print("two")
elif d == 3:
    print("three")
elif d == 4:
    print("four")
elif d == 5:
    print("five")
else:
    print("six")
----

=== Logical Operators

Up until now our conditions in either the while loop or the if-statement have been relatively simple. Python, as do all other programming languages, allow you to state more complicated conditions such as, _if the temperature greater than 50 and less than 100_. We have new Python keywords `and`, `or`, `not`.

==== Logical `and` 

Lets say we rolled a pair of dice and wanted to check if we rolled two ones (snake eyes). Our first attempt, might be:

[source,python,numbered]
----
d1 = random.randrange(6) + 1
d2 = random.randrange(6) + 1

if d1 == 1:
    if d2 == 1:
        print("snake eyes!")
----

This works just fine, albeit a bit clunky. More concise would be to use the logical operator `and`.

[source,python,numbered]
----
d1 = random.randrange(6) + 1
d2 = random.randrange(6) + 1

if d1 == 1 and d2 == 1: <1>
    print("snake eyes!")
----
<1> `and` is a Python keyword.

The logical operator `and` combines a logical value on the left and the right, _X_ `and` _Y_. The entire logical expression is true if both _X_ and _Y_ are true.  We often state this interms of a _truth table_. 

`False` and `True` are Python keywords.

[width="50%", options="header"]
.Logical `and`
|===
| X | Y | X `and` Y

|`False` | `False` | `False`
|`False` | `True` | `False`
|`True` | `False` | `False`
|`True` | `True` | `True`
|=== 

NOTE: A _truth table_ enumerates all possible outcomes of a logical operator for all possible inputs.

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write an if-statement that checks whether an integer `n` is between 0 and 100 inclusive. If it is then set a variable `x` to `0`. Write it two ways, one using a nested if-statement, and the second using the logical `and` operator.

[.result]
====

.Version 1
[source,python,numbered]
----
if n >= 0:
    if n <= 100:
        x = 0
----

.Version 2
[source,python,numbered]
----
if n >= 0 and n <= 100:
    x = 0
----

These are not complete programs as we haven't assigned a value to `n` yet. We will often call these _code fragments_.
====

NOTE: A _code fragment_ is an incomplete segment of Python code. It is not meant to be a complete program.


==== Logical `or` 

Returning to our dice roll, lets check to see if at least one of the dice is a one. Again, your first instinct might be to write this using if-statements alone, which is possible.

[source,python,numbered]
----
d1 = random.randrange(6) + 1
d2 = random.randrange(6) + 1

if d1 == 1:
    print("one")
elif d2 == 1:
    print("one")
----

But a more concise way would be to use the logical `or` operator.

[source,python,numbered]
----
d1 = random.randrange(6) + 1
d2 = random.randrange(6) + 1

if d1 == 1 or d2 == 1: <1>
    print("one")
----
<1> `or` is a Python keyword.

The logical operator `or` combines a logical value on the left and the right, _X_ `or` _Y_. The entire logical expression is true if either one of _X_ or _Y_ is true.  The truth table for logical `or` is: 

[width="50%", options="header"]
.Logical `or`
|===
| X | Y | X `or` Y

|`False` | `False` | `False`
|`False` | `True` | `True`
|`True` | `False` | `True`
|`True` | `True` | `True`
|===

When `and` and `or` are both used in an expression `and` has a higher precedence (much like `*` does over `+`).

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write a code fragment that will determine whether a user rolled exactly one 1. 
Assume variable `d1` and `d2` have values.

[.result]
====
There several ways to write this. Here is one way.

[source,python,numbered]
----
if (d1 == 1 or d2 == 1) and d1 != d2: <1>
    print("exactly one, 1")
----

The parentheses around the `or` are necessary.  Another solution is:

[source,python,numbered]
----
if (d1 == 1 or d2 == 1) and (d1 != 1 or d2 != 1): <1>
    print("exactly one, 1")
----
<1> Note the parentheses, they are necessary.

Yet a third solution is:
[source,python,numbered]
----
if (d1 == 1 and d2 != 1) or (d1 != 1 and d2 == 1):
    print("exactly one, 1")
----
====

==== Logical `not`

The remaining logical operator is `not`, the logical negation of `True` and `False`. The truth table is simply:

[width="25%", options="header"]
.Logical `not`
|===
| X | `not` X

|`False` | `True`
|`True`  | `False`
|===


=== Exercises

.Exercise 1 +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write a function `max2` that returns the larger of the two parameters. For example, `print(max2(9,7))` 
would print `9`.

[.result]
[source,python]
----
def max2(x,y):
    if x > y:
        return x
    else:
        return y
----

.Exercise 2+++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write a function `max3` that returns the maximum of three parameters. For example, `print(max3(4,2,9))` would print `9`.

[.result]
====

[source,python,numbered]
----
def max3(x,y,z):
    if x > y and x > z:    <1>
        return x
    elif y > x and y > z:  <2>
        return y
    else:                  <3>
        return z
----
<1> Is `x` the largest?
<2> Is `y` the largest?
<3> It must be `z`

A more concise way would be to use the function `max2` from the previus
problem. 

[source,python,numbered]
----
def max3(x,y,z):
    return max2(x,max2(y,z)) <1>
----
<1> Recall that this is called _function composition_.

Okay, so none of this was necessary. Python already has a built-in function `max` that can take an arbitrary number of arguments.

[source,python]
----
print(max(4,1))
print(max(4,1,9))
print(max(2,10,4,1))
----

====

.Exercise 3 
Write a function `middle` that returns middle of three numbers. Calling `print(middle(4,1,9))` would print `4`.

.Exercise 4 +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
Write a program that reads three integers from the user and prints `equal` if all three are equal and `not equal` if they are not all the same.

[.result]
[source,python]
----
x = int(input("Enter number: "))
y = int(input("Enter number: "))
z = int(input("Enter number: "))

if x == y and y == z:
    print('equal')
else:
    print('not equal')
----

=== Terminology 

.Terminology
[cols="2"]
|===

a| 
* uniform random number
* code fragment
* truth table

a|
* `and`
* `or`
* `not`

|===
