== The `for` loop

Recall that a very common looping pattern is a _counting loop_ that iterates an
exact number of times. Recall the pattern ...

[source,python,numbered]
----
i = 0
while i < n:
    # loop body
	i = i + 1
----	

This loop will body will execute exactly `n` times; as long as `n` is not modified in the loop body. Another way to write this in Python is using the `for`-loop.

[source,python,numbered]
----
for i in range(n):
    # loop body
----

There are two new Python keywords `for` and `in`. Notice also that there is no explicit assignment statement incrementing `i` by one. There is also the use of this new function  `range(n)` with an argument(n). Technically `range` is not a function in Python but a _range type_ which is used to generate an immutable sequence of integers. Something that is _immutable_ cannot be changed. So `range(n)` generates a sequence of numbers from `0` up to but not including `n`.

The `for`-loop 

[source,python,numbered]
----
for i in range(10):
    print(i)
----

will print the integers 0 through 9, one per line. More generally, the `for`-loop has the syntax ...

[source,python,numbered]
----
for var in some_sequence_type:
    stmt
----

Where `some_sequence_type` represents a sequence of values, such as the sequence of integers generated by the `range` function. The variable `var` will take on each value in the sequence, and `var` can be used in the loop body, but `var` should not be modified in the loop body.

=== `for` loop examples

Here is an example for loop that will sum the integers from 1 to 100.

[source,python,numbered]
----
total = 0
for i in range(101):
    total = total + i
----

The `range` function can take an optional starting value. For example `range(10,15)` generates the sequence of integers `10, 11, 12, 13, 14`.

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
What is the output of the following code fragment.

[source,python,numbered]
----
sum = 0
for i in range(3,8):
    sum += i
print(sum)
----

[.result]
====
25
====

We don't always have to use the `range` function to generate a sequence. A string literal is  also a sequence of characters.

.Example

[source,python,numbered]
----
x = 3 + 5 * 9
print(x)
----

[.result]
====
`48`
====


[source,python,numbered]
----
name = "Tom Marvolo Riddle"
for ch in name:
    print(ch)
----

will print each character in the string literal `"Tom Marvolo Riddle"` on a separate line. So a string is a sequence type. We will see one more important sequence type later on called a _list_.

=== Exercises

Lots of `for`-loop exercises

=== Terminology 

.Terminology
[cols="2"]
|===

a|
 * sequence type

a|
 * immutable

|===

