== The `for` loop

Recall that a very common looping pattern is a _counting loop_ that iterates an
exact number of times. Recall the pattern ...

[source,python,numbered]
----
i = 0
while i < n:
    # loop body
	i = i + 1
----	

This loop body will execute exactly `n` times; as long as `n` is not modified in the loop body. Another way to write this in Python is using the `for`-loop.

[source,python,numbered]
----
for i in range(n):
    # loop body
----

There are two new Python keywords `for` and `in`. There is also no explicit assignment statement incrementing `i` by one. There is also the use of this new function  `range(n)` with an argument `n`. Technically `range` is not a function in Python but a _range type_ which is used to generate an immutable sequence of integers. Something that is _immutable_ cannot be changed. So `range(n)` generates a sequence of numbers from `0` up to but not including `n`.

The `for`-loop 

[source,python,numbered]
----
for i in range(10):
    print(i)
----

will print the integers 0 through 9, one per line. More generally, the `for`-loop has the syntax ...

[source,python,numbered]
----
for var in some_sequence_type:
    stmt
----

Where `some_sequence_type` represents a sequence of values, such as the sequence of integers generated by the `range` function. The variable `var` will take on each value in the sequence, and `var` can be used in the loop body, but `var` should never be modified in the loop body.

=== `for` loop examples

Here is an example `for`-loop that will sum the integers from 1 to 100.

[source,python,numbered]
----
total = 0
for i in range(101):
    total = total + i
----

The `range` function can take an optional starting value. For example `range(10,15)` generates the sequence of integers `10, 11, 12, 13, 14` (it never includes the _stop_ value, in this case `15`).

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
[source,python,numbered]
----
# What is the output of the following code?
sum = 0
for i in range(3,8):
    sum += i
print(sum)
----

[.result]
====
----
25
----
Because `3+4+5+6+7` is `25`.
====

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
[source,python,numbered]
----
# What is the output of the following code?
sum = 0
for i in range(8,3):
    sum += i
print(sum)
----

[.result]
====
----
0
----
Because the start value in the `range` function is greater-than-or-equal to the stop value, 
the loop iterates exactly zero times.
====

The range function can also take an optional _step_ value as the third argument. For example, `range(10,15,2)` generates the sequence of integers `10, 12, 14`.

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
[source,python,numbered]
----
# What is the output of the following code?
sum = 0
for i in range(3,8,2):
    sum += i
print(sum)
----

[.result]
====
----
15
----
Because `3+5+7` is `15`.
====

Step values can be negative. For example, `range(8,3,-1)` generates the sequence
`8,7,6,5,4` (why does it not include `3`? Because the `range` function never includes the 
final _stop_ value, in this case `3`).

=== Nested `for`-loops

`for`-loops can be nested just like `while` loops. This is a pattern we will see frequently when we get to processing images in pygame. Consider the code fragment below:

[source,python,numbered]
----
for i in range(4):
    for j in range(3):
        print(i,'\t',j)
----

For each value of `i` in the _outer_ `for`-loop `j` will take on values `0`,`1`, and `2` in the _inner_ `for`-loop. The output produced is:

----
0 	 0
0 	 1
0 	 2
1 	 0
1 	 1
1 	 2
2 	 0
2 	 1
2 	 2
3 	 0
3 	 1
3 	 2
----

This one is slightly more tricky, but one you will see again.

.Check Yourself +++<span style='color:red;margin-right:1.25em; display:inline-block;'>&nbsp;&nbsp;&nbsp;</span>+++
[source,python,numbered]
----
# What is the output of the following code?
for i in range(4):
    for j in range(i,3):
        print(i,'\t',j)
----

[.result]
====
The way to think of this is that for each value `i` `j` will take on value from `i` 
up to but not including `3`.
----
0 	 0
0 	 1
0 	 2
1 	 1
1 	 2
2 	 2
----

====

=== Other kinds of `for`-loops

Later on we will see `for`-loops that don't use integer ranges. That is, we will not always use the `range` function to generate a sequence for the `for`-loop. A string literal is  also a _sequence type_, it is a sequence of characters. The code

[source,python,numbered]
----
name = "Tom Marvolo Riddle"
for ch in name:
    print(ch)
----

will print each character in the string literal `"Tom Marvolo Riddle"` on a separate line. So a string is a sequence type. We will see several more sequence types, including strings, in later chapters. 


=== Exercises

TBD

=== Terminology 

.Terminology
[cols="2"]
|===

a|
 * sequence type
 * range type
 * start, stop, and step values

a|
 * immutable
 * outer loop
 * inner loop

|===

