An Introduction to Computer Science and Programming with Python
===============================================================
Ed Harcourt <edharcourt@stlawu.edu>
v0.2, July 2018:
:toc: right
:doctype: book
:toclevels: 2
:numbered:
:sectanchors:
:icons: font
:source-highlighter: pygments
:stem: latexmath
:imagesdir: ./images
:includedir: .
:docinfo: shared,private-head

////
http://www.petercollingridge.co.uk/pygame-physics-simulation/collisions
http://www.petercollingridge.co.uk/book/export/html/6
http://www.petercollingridge.co.uk/book
https://stackoverflow.com/questions/101268/hidden-features-of-python/1024693
http://a-little-book-of-r-for-bioinformatics.readthedocs.io/en/latest/index.html
http://codingbat.com/python
https://www.scipy-lectures.org/

////

[watermark]#DRAFT#

_Department of Mathematics, Computer Science, and Statistics_ +
St. Lawrence University +
Canton, NY 13625

include::frontmatter.adoc[]

include::ch1-introduction.adoc[]

include::ch2-pygame-intro.adoc[]

include::ch3-functions.adoc[]

include::ch4-repetition-the-while-loop.adoc[]

include::ch5-conditionals.adoc[]

include::ch6-a-random-walk.adoc[]

////
include::ch7-case-study-particles-and-collisions.adoc[]

include::ch8-the-for-loop.adoc[]

include::ch9-event-handling.adoc[]

include::ch10-image-processing.adoc[]

include::ch11-string-and-file-processing.adoc[]

include::ch12-cryptography.adoc[]

include::ch13-accessing-the-web.adoc[]

include::ch14-tuples-and-lists.adoc[]
////

[bibliography]
== References and Reading

Students often ask me about books and resources. Here are some of my goto references, when I'm looking for ideas, examples, or maybe just a new way to try and explain a difficult concept.

. John MacCormick. _Nine Algorithms that Changed the World_. Princeton University Press. 2012.
. Harrison Kinsley and Will McGugan. _Beginning Python Games Development with Pygame_. Second Edition. Apress. 2015.
. Robert Sedgewick and Kevin Wayne. _Computer Science, An Interdisciplinary Approach_. Addison Wesley. 2017.
. Mark Lutz. _Learning Python_. Fifth Edition. O'Reilly. 2013. 
. Bruce Schneier. _Applied Cryptography_. Second Edition. Wiley. 1996.
. David Harel with Yishai Feldman. _Algorithmics, The Spirit of Computing_. Third Edition. Addison Wesley. 2004.
. Iwo Bialynicki-Birula and Iwona Bialynicka-Birula. _Modeling Reality, How Computers Mirror Life_. Oxford University Press. 2004.
. Sarah Flannery with David Flannery. _In Code, A Young Woman's Mathematical Journey_. Algonquin Books of Chapel Hill. 2002.
. Leonard Mlodinow. _The Drunkard's Walk, How Randomness Rules Our Lives_. Pantheon. 2008.
. David Harel. _Computers Ltd. What They Really Can't Do_. Oxford University Press. 2000.
. Ian Stewart. _In Pursuit of the Unknown_. Basic Books. 2012.
. Elizabeth Allman and John Rhodes. _Mathematical Models in Biology, An Introduction_. Cambridge Univeristy Press. 2004.
. Mitchell Resnick. _Turles, Termites, and Traffic Jams, Explorations in Massivey Parallel Microworlds_. The MIT Press. 1994.
. Charles Petzold. _CODE, The Hidden Language of Computer Hardware and Software_. Microsoft Press. 2000.
. Donella Meadows. _Thinking In Systems, A Primer_. Chelsea Green. 2008.
. Nigel Gilbert. _Agent Based Models_. Sage Publishing. 2008.


////
[appendix]

== Installing Python, Pygame, and Pycharm

=== Installing Python

=== Installing Pygame

=== Installing Pycharm

[appendix]

== Python Functions

This is by no means a refereance manual or exhaustive. This only covers functions and 
modules we have encountered in this text.

=== Builtin Functions

* `len(obj)`
* `print(args)`
* `str(obj)`
* `int(obj)`
* `float(obj)`
* `input(prompt)`
* `abs(number)`
* `min(args)`
* `max(args)`
* `round(n,d)`

https://docs.python.org/3/library/functions.html

=== The Random Module

* `import random`
* `random.randrange(n)`
* `random.random()`

=== The Math Module

* `import math`
* `math.sqrt(n)`
* `math.pi`

https://docs.python.org/3/library/math.html

=== The Pygame Module

* `import pygame`
* `pygame.display.set_mode((w,h))`

////

